### ISSUE TITLE
Could you please share the code to plot ECE histogram?

### ISSUE THREAD

**Issue by mitming** [markus93/NN_calibration#12]

**Comment by markus93** [comment]
Hey!

[Here](https://github.com/dirichletcal/experiments_dnn/blob/master/scripts/notebooks/Reliability%20Diagrams%20of%20Dirichlet%20(Figure%201%20and%20Supp.%20Figure%2012).ipynb) is a link to a notebook for generating reliability diagrams. Check the "rel_diagram_sub2" function, the "accs" correspond to the average accuracies for each bin, and "confs" correspond to the average confidence of each bin.

All the best,
Markus

**Comment by mitming** [comment]
> Hey!
> 
> [Here](https://github.com/dirichletcal/experiments_dnn/blob/master/scripts/notebooks/Reliability%20Diagrams%20of%20Dirichlet%20(Figure%201%20and%20Supp.%20Figure%2012).ipynb) is a link to a notebook for generating reliability diagrams. Check the "rel_diagram_sub2" function, the "accs" correspond to the average accuracies for each bin, and "confs" correspond to the average confidence of each bin.
> 
> All the best, Markus

Thanks a lot!
